@startuml
class Persona{
// atributos
- String dni
- String nombre
- String apellidos
- int anioNacimiento
- int anioObtencionCarnet
- LocalDate fechaCaducidadCarnet

// Constructor()
+ Persona (atributos....)

// Getters & Setters ()
+ getDni() : String
+ getNombre() : String
+ getApellidos() : String
+ getAnioNacimiento() : int
+ getAnioObtencionCarnet() : int
+ getFechaCaducidadCarnet() : LocalDate
+ setDni(String dni) : void
+ setNombre(String nombre) : void
+ setApellidos(String apellidos) : void
+ setAnioNacimiento(int anioNacimiento) : void
+ setAnioObtencionCarnet(int anioObtencionCarnet) : void
+ setFechaCaducidadCarnet(LocalDate fechaCaducidadCarnet) : void

// Métodos ()
+ toString()
+ ValidarDni(String dni) : boolean

}
@enduml